---
- name: Delete files on a windows server
  hosts: windows
  become: no
  vars_files:
    - vars.yml
  vars:
    matched_files: []
    unmatched_files: []
  tasks:

    - name: Find files in a directory
      win_find:
        paths: "{{ item }}"
        recurse: no  # yes - To search subdirectories as well
        file_type: file  # To only find files (not directories)
      loop: "{{paths}}"
      register: found_files
    
    - name: Show the found files in different paths
      debug:
        msg: "{{ found_files }}"

    - name: Check if files are found in the location
      set_fact:
        matched_files: "{{ matched_files + ([item.filename] if item.filename in files else []) }}"
        unmatched_files: "{{ unmatched_files + ([item.filename] if item.filename not in files else []) }}"
      loop: "{{item.files}}"
      loop: "{{ found_files.results }}"

    - name: show the results
      debug:
        msg: "{{matched_files}}\n{{unmatched_files}}"

    # - name: Stop execution remaining tasks if no matching files are found
    #   ansible.builtin.meta: end_host
    #   when: matched_files | length < 1

    - name: Delete matching files
      win_file:
        path: "{{ path }}\\{{ item }}"
        state: absent
      loop: "{{ matched_files }}"
      register: deleted_files
      when: matched_files | length > 0
    
    - name: Show deleted files
      debug:
        msg: "{{ deleted_files }}"
    
    - name: Check if files deleted skipped or failed
      debug:
        msg: "{{ 'Successfully Deleted: '+item.item if item.changed and item.failed else 'Failed to delete '+item.item }}"
      loop: "{{ deleted_files.results }}"