---
- name: Delete files on a windows server
  hosts: windows
  become: no
  vars_files:
    - vars.yml
  vars:
    matched_files: []
    unmatched_files: []
  tasks:

    - name: Find files in a directory
      win_find:
        paths: "{{path}}"
        recurse: no  # yes - To search subdirectories as well
        file_type: file  # To only find files (not directories)
      register: found_files
    
    - name: Check if files are found in the location
      set_fact:
        matched_files: "{{ matched_files + ([item.filename] if item.filename in files else []) }}"
        unmatched_files: "{{ unmatched_files + ([item.filename] if item.filename not in files else []) }}"
      loop: "{{ found_files.files }}"

    - name: show the results
      debug:
        msg: "{{matched_files}}\n{{unmatched_files}}"

    - name: Stop execution remaining tasks if no matching files are found
      ansible.builtin.meta: end_host
      when: matched_files | length > 0

    - name: Delete matching files
      win_file:
        path: "{{ path | join([item]) }}"
        state: absent
      loop: "{{ matched_files }}"
      when: atched_files | length > 0