---
- name: sampleplaybook
  hosts: localhost
  tasks:
    - name: Print a message
      debug:
        msg: "hellow world!"

- name: practice ansible snippets list files
  hosts: localhost
  become: no
  tasks:
    - name: list file and folders in a directory
      ansible.builtin.find:
        paths: ~/target
      register: output
      failed_when: output.json.rc != 0

    - name: show
      debug:
        msg: "{{output.files | map(attribute='path') | list}}"

    - name: copy all matching files to specified directory
      ansible.builtin.copy:
        src: "{{item.path}}"
        dest: /home/awxadm/copied_etc/
        # mode: u=rw,g=wx,o=r
      loop: "{{output.files}}"
      register: output_list
      when: output.changed
    
    - name: show success or failure
      debug:
        msg: "{{item)}}"
      loop: output_list

