---
- name: sampleplaybook
  hosts: localhost
  tasks:
    - name: Print a message
      debug:
        msg: "hellow world!"

- name: practice ansible snippets list files
  hosts: localhost
  become: no
  tasks:
    - name: list file and folders in a directory
      ansible.builtin.find:
        paths: /home/awxadm/target
      register: output

    - name: show
      debug:
        msg: "{{output.files | map(attribute='path') | list}}"

    - name: copy all matching files to specified directory
      ansible.builtin.copy:
        src: "{{item.path}}"
        dest: /home/awxadm/copied_etc/
        mode: u=rw,g=wx,o=r
      loop: "{{output.files}}"
