---
- name: sampleplaybook
  hosts: localhost
  tasks:
    - name: Print a message
      debug:
        msg: "hellow world!"

- name: practice ansible snippets
  hosts: localhost
  become: yes
  tasks:
    - name: list file and folders in a directory
      ansible.builtin.find:
        paths: /tmp
        recurse: yes
      register: output
    
    - name: show
      debug:
        msg: output