---
- name: sampleplaybook
  hosts: localhost
  tasks:
    - name: Print a message
      debug:
        msg: "hellow world!"

- name: practice ansible snippets list files
  hosts: localhost
  become: true
  tasks:
    - name: list file and folders in a directory
      ansible.builtin.find:
        paths: /etc
      register: output
    
    - name: show
      debug:
        msg: "{{output.files | map(attribute='path') | list}}"

    - name: copy all matching files to specified directory
      ansible.builtin.find:
        src: "{{item.path}}"
        dest: /home/awxadm/copied_etc/
      loop: "{{output.files}}"
