---

- name: using modular approach to build automation
  hosts: localhost
  become: yes
  become_user: awxadm
  tasks:

    - name: fetch tickets
      include_role:
        name: servicenow
        tasks_from: fetch.yml