
#  This line shows the password being injected at playbook runtime, in this case the machine credentials
#  are showing up under ansible_user and ansible_password vars to check what other vars are being injected
#  debug out ansible_password
# - name: print the servicenow creds
#   ansible.builtin.debug:
#     msg: "{{ ansible_user }}, {{ ansible_password }}"
#   ignore_errors: yes
- name: validate filters
  include_role:
    name: servicenow
    tasks_from: validate-filters.yml

- name: show ansible env vars
  ansible.builtin.debug:
    msg: "{{ ansible_env }}"
  when: show_env
  ignore_errors: yes
  
- name: fetch incident data
  uri:
    url: "{{ servicenow_instance }}/api/now/table/incident?sysparm_query={{query}}&sysparm_fields={{servicenow.fields}}"
    method: GET
    headers:
      Authorization: "Basic {{ (servicenow.username + ':' + servicenow.password) | b64encode}}" 
      Accept: application/json
    status_code: 200
    return_content: yes
  register: servicenow_resp
  when: {{ servicenow.checks_passed }}

- name: fetch incident data
  uri:
    url: "{{ servicenow_instance }}/api/now/table/incident"
    method: GET
    headers:
      Authorization: "Basic {{ (servicenow.username + ':' + servicenow.password) | b64encode}}" 
      Accept: application/json
    status_code: 200
    return_content: yes
  register: servicenow_resp
  when: {{ not servicenow.checks_passed }}

- name: create tickets dir to cache ticket contents
  ansible.builtin.file:
    # path: "{{ lookup('ansible.builtin.ENV','HOME') }}/ticket"
    # path: "../{{ playbook_dir }}/ticket"
    path: "{{ path }}/ticket"
    state: directory
  when: write_to_file

- name: save fetched ticket content
  ansible.builtin.copy:
    content: "{{ ticket_details.json }}"
    dest: "{{ path }}/ticket/{{ansible_date_time.date}}.json"
    mode: 0755
  when: write_to_file

- name: show ticket content
  ansible.builtin.debug:
    msg: "{{ ticket_details.json }}"
  when: show_output
    
