- name: initialize validation engine
  set_fact:
    valid_filters_str: ""
    invalid_filters_str: ""

- name: start validation engine
  set_fact:
    valid_filters_str: |
      {% set valids = {} %}
      {% for key,val in servicenow['filters'].items() %}
        {% if val is mapping and True in val.values() and "" not in val.values() %}
          {% set _ = valids.update({key: val}) %}
        {% endif %}
      {% endfor %}
      {{ valids }}
    invalid_filters_str: |
      {% set invalids = {} %}
        {% for key,val in servicenow['filters'].items() %}
          {% if val is mapping and True in val.values() and "" in val.values() %}
            {% set _ = invalids.update({key: val}) %}
          {% endif %}
        {% endfor %}
      {{ invalids }}

- name: initialize validation facts
  set_fact:
    validate:
      isinvalid: "{{ invalid_filters_str.splitlines() | map('from_yaml') | list}}"
      isvalid: "{{ valid_filters_str.splitlines() | map('from_yaml') | list}}"
      
- name: show validation result
  ansible.builtin.debug:
    msg: "{{ validate }}"
  ignore_errors: yes
  when: show_output

- name: fail if filter params are incorrect
  fail:
    msg: >-
      Invalid configuration for filter {{ item.key }}.
      The Field: {{ (item.value | list) [0] }} cannot be blank when {{ (item.values() | list) [1] }} is 'True'.
      Please set the configuration settings correctly by setting proper values for {{ (item.values() | list) [0] }}
  with_dict: "{{ validate.isinvalid }}"
  when: validate.isinvalid | length > 0

  - name: build sys_param query
    set_fact:
      sysparam_query: >-
        {% set query = [] %}
        {% for item in validate['isvalid'] %}
          {% set name = (item.items() | list)[0] %}
          {% set val = (name[1].items() | list)[0] %}
          {% set _ = query.append(name[0] ~ "=" ~ val) %}
          {% set _ = query.append(name[0] ~ "=" ~ val) %}
        {% endfor %}
        {{ query | join("^") }}

- name: show sysparam query
  ansible.builtin.debug:
    msg: "{{ sysparam_query }}"
  when: show_output
